### PR TITLE
add a fast path in parallel scan

### LINKED ISSUE #38: parallel_scan rejects arrays not larger than pool size
```
utop # #require "domainslib";;
utop # open Domainslib;;
utop # let p = Task.setup_pool 4;;
val p : Task.pool = <abstr>
utop # Task.parallel_scan p (+) [|1;2;3;4|];;
Exception: Invalid_argument "index out of bounds".
```

### PR DESCRIPTION
**Pull request by Sudha247**
Parallel scan runs a sequential version when the number of elements in the array is less than the number of domains in the pool or when the number of domains in the pool is one. Fixes #38.

### CODE REVIEW

**Review by kayceesrk — APPROVED** [review]
LGTM!

**Comment by Sudha247** [comment]
@nilsbecker we were wondering if you had any thoughts on this before merging.

**Comment by nilsbecker** [comment]
hi, one thought is that there could be a scenario where sequential evaluation for small arrays may not be the best option. for example the pool has 10 workers and the array has 8 elements, but each `op` operation takes a couple seconds. then one would miss out on parallel speedup by doing the 8 elements sequentially, no?

**Comment by Sudha247** [comment]
Closing in favour of #60

**Pull request closed without merging**
